matrix:
  include:
  - language: clojure
    lein: lein
    services: mysql
    cache:
      npm: true
      directories:
        - client/node_modules
        - client/.cache
    addons:
      apt:
        packages:
          - libgconf-2-4
    script:
    - cd ..
    - sleep 1m
    - npx cypress run
    before_script:
    - npm install

    before_install:
    - export NODE_ENV=travis
    - cd server
    - npm init -y
    - npm install mysql2 --save
    - npm install sequelize --save
    - npm install npx -g
    - npm install sequelize-cli --save
    - mysql -e 'CREATE DATABASE IF NOT EXISTS coffeepot_travis;'
    - npx sequelize db:migrate
    - npx sequelize db:seed:all
    - lein ring server &
    - cd ..
    - cd client
    - lein deps
    - lein install
    - lein travis &
