language: clojure
lein: lein
script: 
- touch src/cljs/coffeepot/envconfig.cljs
- echo "(ns coffeepot.envconfig) (def firebase {})" > src/cljs/coffeepot/envconfig.cljs	
- lein cljsbuild once min
- rm src/cljs/coffeepot/envconfig.cljs
